### ISSUE TITLE
Edit Dockerfile to use FROM as builder ??

### ISSUE THREAD

**Issue by bigbrozer** [nVentiveUX/docker-valheim#2]
@link-webcreations if I understand well, you mean to have a stage for doing all the stuff done in the `Dockerfile` and additionally the entry point. We package the whole stuff and we got a final image just to launch the server ?

**Comment by link-webcreations** [comment]
Not sure it's needed.
For now, steamcmd, then the game, are both updated at launch. So to update the game, just need to run `docker retart valheim`.
That's more convenient than pulling a new version of the docker image.
Also no interrest to pin the version, as only the latest will work with the steam valheim client game.
